# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    command: bash -c "npm run build && ./scripts/start.sh"

  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_PASSWORD: postgres
